name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                node: ['10', '13']
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v1
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn
            - run: yarn build
            - run: yarn bootstrap
            - run: yarn test
